/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import homeView from "./home/homeView"
import controul from "./home/controul"
import tuodong from "./home/tuodong"
import boxDown from "./home/boxDown"
import zidan from "./home/zidan"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("home/homeView.js",homeView);
		reg("home/controul.js",controul);
		reg("home/tuodong.js",tuodong);
		reg("home/boxDown.js",boxDown);
		reg("home/zidan.js",zidan);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "homeView.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
